version: '3'

services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Shanghai
    ports:
      - "18096:8096"
    volumes:
      - /home/sanzo/software/jellyfin/config:/config
      - /home/sanzo/nvme/share:/media
      - /home/sanzo/softwareOB/jellyfin/cache:/cache
    restart: unless-stopped

