version: '3'

services:
  webdav:
    image: ugeek/webdav:arm
    container_name: webdav
    restart: always
    ports:
      - "18888:80"
    environment:
      - AUTH_TYPE=Digest
      - USERNAME=sanzo
      - PASSWORD=sanzo@webdav
      - LOCATION=/webdav
      - TZ=Asia/Shanghai
    volumes:
      - /home/sanzo/disk:/media
      - /home/sanzo/software/config/docker/webdav/conf-enabled:/usr/local/apache2/conf/conf-enabled/
    # detach: true
